spring.application.name=agrosense-frontend
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.web.locale=es_CO
spring.web.locale-resolver=fixed
spring.messages.fallback-to-system-locale=false

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:true}
server.servlet.session.timeout=30m
server.error.include-stacktrace=never
server.error.include-message=never
